import { useState } from 'react';
import { Upload, AlertCircle, CheckCircle, XCircle, Loader2 } from 'lucide-react';
import { useHistory } from '../context/HistoryContext';
import { ShareToCommunity } from './ShareToCommunity';

interface DetectionResult {
  isAIGenerated: boolean;
  confidence: number;
  analysis: {
    label: string;
    score: number;
  }[];
  details: string;
}

export function ImageDetector() {
  const [image, setImage] = useState<string | null>(null);
  const [fileName, setFileName] = useState<string>('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<DetectionResult | null>(null);
  const { addToHistory } = useHistory();

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setFileName(file.name);
      const reader = new FileReader();
      reader.onload = (event) => {
        setImage(event.target?.result as string);
        setResult(null);
      };
      reader.readAsDataURL(file);
    }
  };

  const analyzeImage = () => {
    setIsAnalyzing(true);
    setResult(null);

    // Mock analysis with realistic delay
    setTimeout(() => {
      const isAI = Math.random() > 0.5;
      const confidence = isAI ? 75 + Math.random() * 20 : 60 + Math.random() * 25;

      const analysisResult = {
        isAIGenerated: isAI,
        confidence: Math.round(confidence * 10) / 10,
        analysis: [
          { label: 'Noise Pattern Analysis', score: Math.random() * 100 },
          { label: 'GAN Artifacts', score: Math.random() * 100 },
          { label: 'JPEG Compression', score: Math.random() * 100 },
          { label: 'Color Distribution', score: Math.random() * 100 },
          { label: 'Frequency Analysis', score: Math.random() * 100 },
        ],
        details: isAI
          ? 'This image shows characteristics typical of AI-generated content, including unusual noise patterns and GAN artifacts.'
          : 'This image appears to be authentic, with natural compression artifacts and realistic noise patterns.',
      };

      setResult(analysisResult);
      
      // Add to history
      addToHistory({
        type: 'image',
        isAIGenerated: analysisResult.isAIGenerated,
        confidence: analysisResult.confidence,
        metadata: {
          fileName: fileName || 'Unknown file',
        },
      });
      
      setIsAnalyzing(false);
    }, 2500);
  };

  return (
    <div className="space-y-6">
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
        <h2 className="text-gray-900 mb-2">AI Image Detection</h2>
        <p className="text-gray-600 mb-6">
          Upload an image to analyze whether it was generated by AI tools like DALL-E, Midjourney, or Stable Diffusion
        </p>

        {/* Upload Area */}
        <div className="space-y-4">
          <label
            htmlFor="image-upload"
            className="flex flex-col items-center justify-center w-full h-64 border-2 border-dashed border-gray-300 rounded-lg cursor-pointer hover:border-blue-500 hover:bg-blue-50 transition-colors"
          >
            {image ? (
              <img src={image} alt="Uploaded" className="max-h-full max-w-full object-contain rounded-lg" />
            ) : (
              <div className="flex flex-col items-center justify-center pt-5 pb-6">
                <Upload className="w-12 h-12 text-gray-400 mb-3" />
                <p className="mb-2 text-gray-700">
                  <span className="font-semibold">Click to upload</span> or drag and drop
                </p>
                <p className="text-gray-500">PNG, JPG, WEBP (MAX. 10MB)</p>
              </div>
            )}
            <input
              id="image-upload"
              type="file"
              className="hidden"
              accept="image/*"
              onChange={handleImageUpload}
            />
          </label>

          {image && !result && (
            <button
              onClick={analyzeImage}
              disabled={isAnalyzing}
              className="w-full bg-[#018790] text-white py-3 rounded-lg hover:bg-[#005461] transition-colors disabled:bg-gray-400 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {isAnalyzing ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Analyzing Image...
                </>
              ) : (
                'Analyze Image'
              )}
            </button>
          )}
        </div>
      </div>

      {/* Results */}
      {result && (
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 space-y-6">
          <div className="flex items-start gap-4">
            {result.isAIGenerated ? (
              <div className="bg-red-100 p-3 rounded-full">
                <XCircle className="w-6 h-6 text-red-600" />
              </div>
            ) : (
              <div className="bg-green-100 p-3 rounded-full">
                <CheckCircle className="w-6 h-6 text-green-600" />
              </div>
            )}
            <div className="flex-1">
              <h3 className="text-gray-900 mb-1">
                {result.isAIGenerated ? 'AI-Generated Content Detected' : 'Authentic Image'}
              </h3>
              <p className="text-gray-600 mb-3">{result.details}</p>
              <div className="flex items-center gap-2">
                <span className="text-gray-700">Confidence:</span>
                <div className="flex-1 bg-gray-200 rounded-full h-2 max-w-xs">
                  <div
                    className={`h-2 rounded-full ${
                      result.isAIGenerated ? 'bg-red-600' : 'bg-green-600'
                    }`}
                    style={{ width: `${result.confidence}%` }}
                  />
                </div>
                <span className="text-gray-900">{result.confidence}%</span>
              </div>
            </div>
          </div>

          {/* Share Button */}
          <div className="flex justify-end border-t border-gray-200 pt-4">
            <ShareToCommunity
              type="image"
              isAIGenerated={result.isAIGenerated}
              confidence={result.confidence}
              metadata={{ fileName: fileName || 'Unknown file' }}
            />
          </div>

          <div className="border-t border-gray-200 pt-6">
            <h4 className="text-gray-900 mb-4">Detailed Analysis</h4>
            <div className="space-y-3">
              {result.analysis.map((item, index) => (
                <div key={index} className="flex items-center gap-3">
                  <span className="text-gray-700 w-48">{item.label}</span>
                  <div className="flex-1 bg-gray-200 rounded-full h-2">
                    <div
                      className="h-2 rounded-full bg-[#018790]"
                      style={{ width: `${item.score}%` }}
                    />
                  </div>
                  <span className="text-gray-600 w-12 text-right">{Math.round(item.score)}%</span>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 flex gap-3">
            <AlertCircle className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
            <p className="text-blue-900">
              This is a demonstration using mock analysis. In a production environment, this would use trained ML models
              to detect AI-generated images.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}