import { useState } from 'react';
import { AlertCircle, CheckCircle, XCircle, Loader2, FileText } from 'lucide-react';
import { useHistory } from '../context/HistoryContext';
import { ShareToCommunity } from './ShareToCommunity';

interface TextAnalysis {
  isAIGenerated: boolean;
  confidence: number;
  metrics: {
    perplexity: number;
    burstiness: number;
    predictability: number;
    vocabularyDiversity: number;
  };
  likelySource: string;
  details: string;
}

export function TextDetector() {
  const [text, setText] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<TextAnalysis | null>(null);
  const { addToHistory } = useHistory();

  const analyzeText = () => {
    if (!text.trim()) return;

    setIsAnalyzing(true);
    setResult(null);

    setTimeout(() => {
      const isAI = Math.random() > 0.5;
      const confidence = isAI ? 72 + Math.random() * 23 : 68 + Math.random() * 20;

      const sources = ['GPT-4', 'Claude', 'Gemini', 'Human Writer'];
      const aiSource = sources[Math.floor(Math.random() * 3)];

      const analysisResult = {
        isAIGenerated: isAI,
        confidence: Math.round(confidence * 10) / 10,
        metrics: {
          perplexity: Math.round((isAI ? 15 + Math.random() * 25 : 40 + Math.random() * 40) * 10) / 10,
          burstiness: Math.round((isAI ? 20 + Math.random() * 30 : 55 + Math.random() * 35) * 10) / 10,
          predictability: Math.round((isAI ? 65 + Math.random() * 30 : 35 + Math.random() * 35) * 10) / 10,
          vocabularyDiversity: Math.round((45 + Math.random() * 45) * 10) / 10,
        },
        likelySource: isAI ? aiSource : 'Human Writer',
        details: isAI
          ? 'Text exhibits patterns consistent with AI language models, including uniform sentence structure, high predictability, and low perplexity scores.'
          : 'Text shows natural human writing patterns with varied sentence structures, emotional nuances, and unpredictable phrasing.',
      };

      setResult(analysisResult);
      
      // Add to history
      addToHistory({
        type: 'text',
        isAIGenerated: analysisResult.isAIGenerated,
        confidence: analysisResult.confidence,
        preview: text.substring(0, 150),
        metadata: {
          textLength: text.length,
        },
      });
      
      setIsAnalyzing(false);
    }, 2000);
  };

  const exampleTexts = [
    {
      label: 'Academic Essay',
      text: 'The impact of artificial intelligence on modern society represents a paradigm shift in human-technology interaction. This technological evolution has fundamentally transformed various sectors, including healthcare, education, and commerce. While the benefits are substantial, it is crucial to address the ethical implications and potential societal disruptions that may arise from widespread AI adoption.',
    },
    {
      label: 'Creative Writing',
      text: "I couldn't believe it. The coffee shop was empty—totally empty. Where was everyone? It's Monday morning, for crying out loud! But there I was, standing in this weird silence, holding my phone like it might explain everything. It didn't.",
    },
    {
      label: 'Technical Content',
      text: 'To implement the authentication system, we need to configure JWT tokens with a 24-hour expiration. The middleware should validate tokens on protected routes and return 401 status codes for unauthorized requests. This approach ensures secure access control while maintaining optimal performance.',
    },
  ];

  return (
    <div className="space-y-6">
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
        <h2 className="text-gray-900 mb-2">AI Text Detection</h2>
        <p className="text-gray-600 mb-6">
          Paste text to analyze whether it was generated by AI models like ChatGPT, Claude, or Gemini
        </p>

        <div className="space-y-4">
          <div>
            <label htmlFor="text-input" className="block text-gray-700 mb-2">
              Enter or paste text to analyze
            </label>
            <textarea
              id="text-input"
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder="Type or paste your text here..."
              rows={10}
              className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
            />
            <p className="text-sm text-gray-500 mt-2">{text.length} characters</p>
          </div>

          <div className="flex flex-wrap gap-2">
            <span className="text-sm text-gray-600">Try examples:</span>
            {exampleTexts.map((example, index) => (
              <button
                key={index}
                onClick={() => {
                  setText(example.text);
                  setResult(null);
                }}
                className="text-sm bg-gray-100 hover:bg-gray-200 text-gray-700 px-3 py-1 rounded-full transition-colors"
              >
                {example.label}
              </button>
            ))}
          </div>

          <button
            onClick={analyzeText}
            disabled={!text.trim() || isAnalyzing}
            className="w-full bg-[#018790] text-white py-3 rounded-lg hover:bg-[#005461] transition-colors disabled:bg-gray-400 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          >
            {isAnalyzing ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                Analyzing Text...
              </>
            ) : (
              <>
                <FileText className="w-5 h-5" />
                Analyze Text
              </>
            )}
          </button>
        </div>
      </div>

      {result && (
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 space-y-6">
          <div className="flex items-start gap-4">
            {result.isAIGenerated ? (
              <div className="bg-red-100 p-3 rounded-full">
                <XCircle className="w-6 h-6 text-red-600" />
              </div>
            ) : (
              <div className="bg-green-100 p-3 rounded-full">
                <CheckCircle className="w-6 h-6 text-green-600" />
              </div>
            )}
            <div className="flex-1">
              <h3 className="text-gray-900 mb-1">
                {result.isAIGenerated ? 'AI-Generated Text Detected' : 'Human-Written Text'}
              </h3>
              <p className="text-gray-600 mb-3">{result.details}</p>
              <div className="flex items-center gap-2">
                <span className="text-gray-700">Confidence:</span>
                <div className="flex-1 bg-gray-200 rounded-full h-2 max-w-xs">
                  <div
                    className={`h-2 rounded-full ${
                      result.isAIGenerated ? 'bg-red-600' : 'bg-green-600'
                    }`}
                    style={{ width: `${result.confidence}%` }}
                  />
                </div>
                <span className="text-gray-900">{result.confidence}%</span>
              </div>
              <p className="text-gray-600 mt-2">
                Likely Source: <span className="text-gray-900">{result.likelySource}</span>
              </p>
            </div>
          </div>

          {/* Share Button */}
          <div className="flex justify-end border-t border-gray-200 pt-4">
            <ShareToCommunity
              type="text"
              isAIGenerated={result.isAIGenerated}
              confidence={result.confidence}
              preview={text.substring(0, 150)}
              metadata={{ textLength: text.length }}
            />
          </div>

          <div className="border-t border-gray-200 pt-6">
            <h4 className="text-gray-900 mb-4">Linguistic Metrics</h4>
            <div className="grid sm:grid-cols-2 gap-4">
              <div className="bg-gray-50 rounded-lg p-4">
                <div className="flex justify-between items-center mb-2">
                  <span className="text-gray-700">Perplexity</span>
                  <span className="text-gray-900">{result.metrics.perplexity}</span>
                </div>
                <div className="bg-gray-200 rounded-full h-2">
                  <div
                    className="h-2 rounded-full bg-[#005461]"
                    style={{ width: `${Math.min(result.metrics.perplexity, 100)}%` }}
                  />
                </div>
                <p className="text-xs text-gray-600 mt-1">Lower = More predictable/AI-like</p>
              </div>

              <div className="bg-gray-50 rounded-lg p-4">
                <div className="flex justify-between items-center mb-2">
                  <span className="text-gray-700">Burstiness</span>
                  <span className="text-gray-900">{result.metrics.burstiness}</span>
                </div>
                <div className="bg-gray-200 rounded-full h-2">
                  <div
                    className="h-2 rounded-full bg-[#018790]"
                    style={{ width: `${result.metrics.burstiness}%` }}
                  />
                </div>
                <p className="text-xs text-gray-600 mt-1">Higher = More human-like variation</p>
              </div>

              <div className="bg-gray-50 rounded-lg p-4">
                <div className="flex justify-between items-center mb-2">
                  <span className="text-gray-700">Predictability</span>
                  <span className="text-gray-900">{result.metrics.predictability}%</span>
                </div>
                <div className="bg-gray-200 rounded-full h-2">
                  <div
                    className="h-2 rounded-full bg-[#00B7B5]"
                    style={{ width: `${result.metrics.predictability}%` }}
                  />
                </div>
                <p className="text-xs text-gray-600 mt-1">Higher = More AI-like patterns</p>
              </div>

              <div className="bg-gray-50 rounded-lg p-4">
                <div className="flex justify-between items-center mb-2">
                  <span className="text-gray-700">Vocabulary Diversity</span>
                  <span className="text-gray-900">{result.metrics.vocabularyDiversity}%</span>
                </div>
                <div className="bg-gray-200 rounded-full h-2">
                  <div
                    className="h-2 rounded-full bg-green-600"
                    style={{ width: `${result.metrics.vocabularyDiversity}%` }}
                  />
                </div>
                <p className="text-xs text-gray-600 mt-1">Measures lexical richness</p>
              </div>
            </div>
          </div>

          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 flex gap-3">
            <AlertCircle className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
            <p className="text-blue-900">
              This is a demonstration. Real text detection would use models trained on linguistic patterns,
              statistical analysis, and machine learning classifiers.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}